#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

message=$(cat "$1")
echo $message

# if [ $message -eq 'major' ]; then
#   echo "major"
#   npm version major
# elif [ $message -eq 'minor' ]; then
#   echo "minor"
#   npm version minor
# else
#   echo "patch"
#   npm version patch
# fi
